eureka:
  client:
    instance:
      hostname: localhost  # Explicitly set the hostname to localhost
      prefer-ip-address: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}  # Eureka Server URL (uses environment variable EUREKA_SERVER_URL if available)
    fetch-registry: true  # Allows the client to fetch the service registry from Eureka Server
    register-with-eureka: true
